config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users do
    resources :posts do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  # Available modules are: :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Associations
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  # Attributes
  attribute :name, :string
  attribute :bio, :text
  attribute :posts_counter, :integer, default: 0
  attribute :photo, :string

  # Validations
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Methods
  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :find_user, only: [:show]

  def index
    @users = User.includes(:posts).all
  end

  def show
    @three_recent_posts = @user.three_most_recent_posts unless @user.nil?
  end

  def new; end

  def find_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Handle the situation when the post is not found
    flash[:alert] = 'User not found, back to users page'
    redirect_to users_path
  end
end

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% unless @users.nil? %>
    <% @users.each do |user| %>
      <a href="<%= user_posts_path(user) %>">
        <div class="user-box">
          <%= render partial: 'shared/user_details', locals: { user: user } %>
        </div>
      </a>
    <% end %>
  <% else %>
    <p>Please sign in or sign up to view user details.</p>
    <%= link_to 'Sign In', new_user_session_path %>
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
</ul>

app/views/users/show.html.erb
<a href="<%= user_posts_path(@user) %>">
    <button id="back-btn">⬅</button>
</a>
<div class="user-box">
    <%= render partial: 'shared/user_details', locals: { user: @user } %>
</div>
<div class="bio">
    <h3>Bio</h3>
    <p>
        <%= @user.bio %>
    </p>
</div>
<% @three_recent_posts.each do |post| %>
    <a href="<%= user_post_path(@user, post) %>">
        <div class="post bio">
            <h3>Post <%= raw "#" + post.id.to_s %></h3>
            <p><%= post.text %></p>
            <div class='post-interactions'>
                <span>Comments: <%= post.comments_counter %>,</span>
                <span>Likes: <%= post.likes_counter %></span>
            </div>
        </div>
    </a>
<% end %>
<a href="<%= user_posts_path(@user) %>">
    <button id="pagination">See all posts</button>
</a>